name: Build and Push Docker Image

on:
  push:
    branches:
      - trunk


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Check if PATH_VERSION exists and increment
    - name: Check and increment PATH_VERSION
      id: version
      run: |
        # Try to get PATH_VERSION, exit if it doesn't exist
        if ! CURRENT_VERSION=$(gh variable get PATH_VERSION); then
          echo "Error: PATH_VERSION variable is not set in repository variables"
          exit 1
        fi
        
        # Increment the version
        NEW_VERSION=$((CURRENT_VERSION + 1))
        
        # Set output for later steps
        echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        
        # Update repository variable using gh cli
        gh variable set PATH_VERSION -b"${NEW_VERSION}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/github-actions-runner:latest
          your-dockerhub-username/github-actions-runner:1.0.${{ steps.version.outputs.new_version }}
        build-args: |
          RUNNER_VERSION=2.320.0